/* ============================================
   SacraDigit — display preferences
   Light/Dark theme + English/Filipino, for every
   role (admin, parishioner, ITech, Media). Each
   role's shell script calls initUiPrefs(), which
   puts both controls in the top bar next to the
   date and the (?) help button.

   Saved per browser (localStorage):
     sacradigit_theme = 'light' | 'dark'
     sacradigit_lang  = 'en' | 'fil'
   A tiny inline script in each page's <head>
   applies the saved theme before the page is
   drawn (no white flash); see THEME_BOOT below.

   Dark colours:  theme-dark.css (generated by
                  tools/build-dark-theme.mjs)
   Filipino text: i18n-fil.js (English → Filipino
                  dictionary), applied by translatePage()
   ============================================ */

const THEME_KEY = 'sacradigit_theme';
const LANG_KEY = 'sacradigit_lang';

/** The inline <head> snippet every page carries (kept here for reference). */
export const THEME_BOOT = `try{var t=localStorage.getItem('${THEME_KEY}');if(t==='dark')document.documentElement.dataset.theme='dark';if(localStorage.getItem('${LANG_KEY}')==='fil'){document.documentElement.lang='fil';document.documentElement.classList.add('i18n-pending');setTimeout(function(){document.documentElement.classList.remove('i18n-pending')},1500)}}catch(e){}`;

const read = (k) => { try { return localStorage.getItem(k); } catch { return null; } };
const write = (k, v) => { try { localStorage.setItem(k, v); } catch { /* private mode */ } };

export const currentTheme = () => (document.documentElement.dataset.theme === 'dark' ? 'dark' : 'light');
export const currentLang = () => (read(LANG_KEY) === 'fil' ? 'fil' : 'en');

export function setTheme(theme) {
  if (theme === 'dark') document.documentElement.dataset.theme = 'dark';
  else delete document.documentElement.dataset.theme;
  write(THEME_KEY, theme);
  document.dispatchEvent(new CustomEvent('sacradigit:theme', { detail: theme }));
}

/* ------------------------------------------
   Translation (English → Filipino)
------------------------------------------ */

let dict = null;        // Map of normalized English → Filipino
let patterns = [];      // [RegExp, replacement] for text with numbers/names in it
let observer = null;
const SKIP_TAGS = new Set(['SCRIPT', 'STYLE', 'NOSCRIPT', 'TEXTAREA', 'CODE', 'PRE', 'svg', 'SVG', 'title']);
const ATTRS = ['placeholder', 'title', 'aria-label'];

const norm = (s) => s.replace(/\s+/g, ' ').trim();

const MONTHS_FIL = { January: 'Enero', February: 'Pebrero', March: 'Marso', April: 'Abril', May: 'Mayo', June: 'Hunyo', July: 'Hulyo', August: 'Agosto', September: 'Setyembre', October: 'Oktubre', November: 'Nobyembre', December: 'Disyembre',
  Jan: 'Ene', Feb: 'Peb', Mar: 'Mar', Apr: 'Abr', Jun: 'Hun', Jul: 'Hul', Aug: 'Ago', Sep: 'Set', Sept: 'Set', Oct: 'Okt', Nov: 'Nob', Dec: 'Dis' };
const DAYS_FIL = { Monday: 'Lunes', Tuesday: 'Martes', Wednesday: 'Miyerkules', Thursday: 'Huwebes', Friday: 'Biyernes', Saturday: 'Sabado', Sunday: 'Linggo',
  Mon: 'Lun', Tue: 'Mar', Wed: 'Miy', Thu: 'Huw', Fri: 'Biy', Sat: 'Sab', Sun: 'Lin' };
const DATE_WORD = new RegExp(`\\b(${[...Object.keys(MONTHS_FIL), ...Object.keys(DAYS_FIL)].sort((a, b) => b.length - a.length).join('|')})\\b`, 'g');
// Only touch month/day names inside something that looks like a date ("Sep 26, 2026", "Saturday, September 26").
const LOOKS_LIKE_DATE = /\b(\d{1,2},?\s+\d{4}|\d{4}|\w+day,|[A-Z][a-z]{2},\s+[A-Z][a-z]{2,8}\s+\d{1,2}|[A-Z][a-z]{2,8}\s+\d{1,2})\b/;

const translateDates = (s) => (LOOKS_LIKE_DATE.test(s) ? s.replace(DATE_WORD, (w) => MONTHS_FIL[w] || DAYS_FIL[w] || w) : s);

function translateOne(key) {
  const hit = dict.get(key);
  if (hit) return hit;
  for (const [re, rep] of patterns) {
    if (re.test(key)) return translateDates(key.replace(re, rep));
  }
  const dated = translateDates(key);
  return dated !== key ? dated : null;
}

function translateText(text) {
  const key = norm(text);
  if (!key) return null;
  const whole = translateOne(key);
  if (whole) return whole;
  // "Pet Blessing · requested for Sat, Sep 12", "First Offering — Made a first…"
  const sep = key.includes(' · ') ? ' · ' : key.includes(' — ') ? ' — ' : null;
  if (!sep) return null;
  const joined = key.split(sep).map(part => translateOne(part) || part).join(sep);
  return joined !== key ? joined : null;
}

/** Translate a piece of text (used by i18n-fil.js patterns for the parts they capture). */
export const t = (s) => (dict && translateText(s)) || s;

function translateTextNode(node) {
  const raw = node.nodeValue;
  if (!raw || !/[A-Za-z]/.test(raw)) return;
  const fil = translateText(raw);
  if (!fil || fil === norm(raw)) return;
  const lead = raw.match(/^\s*/)[0], trail = raw.match(/\s*$/)[0];
  node.nodeValue = lead + fil + trail;
}

function translateAttrs(el) {
  for (const a of ATTRS) {
    const v = el.getAttribute && el.getAttribute(a);
    if (!v) continue;
    const fil = translateText(v);
    if (fil && fil !== v) el.setAttribute(a, fil);
  }
  // <input type="button" value="…">
  if (el.tagName === 'INPUT' && (el.type === 'button' || el.type === 'submit') && el.value) {
    const fil = translateText(el.value);
    if (fil) el.value = fil;
  }
}

// <textarea> content is never translated (people type there), but its placeholder is.
function attrsSkipped(el) {
  return !el || (el.closest && el.closest('[data-no-translate]'));
}

function skipped(el) {
  return !el || SKIP_TAGS.has(el.tagName) || (el.closest && el.closest('[data-no-translate], [contenteditable="true"]'));
}

function translateTree(root) {
  if (root.nodeType === Node.TEXT_NODE) {
    if (!skipped(root.parentElement)) translateTextNode(root);
    return;
  }
  if (root.nodeType !== Node.ELEMENT_NODE) return;
  if (!attrsSkipped(root)) translateAttrs(root);
  if (skipped(root)) return;
  root.querySelectorAll('[placeholder], [title], [aria-label], input[type="button"], input[type="submit"]').forEach(el => { if (!attrsSkipped(el)) translateAttrs(el); });
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
    acceptNode: (n) => (skipped(n.parentElement) ? NodeFilter.FILTER_REJECT : NodeFilter.FILTER_ACCEPT),
  });
  for (let n = walker.nextNode(); n; n = walker.nextNode()) translateTextNode(n);
}

async function startTranslating() {
  if (!dict) {
    const mod = await import('./i18n-fil.js');
    dict = new Map(Object.entries(mod.FIL).map(([en, fil]) => [norm(en), fil]));
    patterns = mod.FIL_PATTERNS || [];
  }
  document.documentElement.lang = 'fil';
  const t = translateText(document.title);
  if (t) document.title = t;
  translateTree(document.body);
  // Keep translating whatever the page adds or changes later (tables, toasts, modals…).
  observer = new MutationObserver((muts) => {
    for (const m of muts) {
      if (m.type === 'characterData') translateTextNode(m.target);
      else if (m.type === 'attributes') translateAttrs(m.target);
      else m.addedNodes.forEach(translateTree);
    }
  });
  observer.observe(document.body, { childList: true, subtree: true, characterData: true, attributes: true, attributeFilter: ATTRS });
}

export async function setLanguage(lang) {
  write(LANG_KEY, lang);
  if (lang === 'fil') {
    await startTranslating();
  } else {
    // Back to English: the original text is simply the page as served.
    window.location.reload();
  }
}

/* ------------------------------------------
   Controls in the top bar
------------------------------------------ */

const STYLE = `
  .i18n-pending body { opacity: 0; }
  .ui-prefs { display: inline-flex; align-items: center; gap: 0.375rem; }
  .ui-prefs-btn, .ui-prefs-lang {
    display: inline-flex; align-items: center; justify-content: center; gap: 0.3rem;
    height: 1.75rem; border-radius: 999px; border: 1.5px solid #c7cad6; background: #ffffff;
    color: #4b5563; font-size: 0.6875rem; font-weight: 700; cursor: pointer;
    transition: background-color 0.15s ease, border-color 0.15s ease, color 0.15s ease;
  }
  .ui-prefs-btn { width: 1.75rem; padding: 0; }
  .ui-prefs-btn svg { width: 0.95rem; height: 0.95rem; }
  .ui-prefs-lang { padding: 0 0.5rem 0 0.45rem; }
  .ui-prefs-lang svg { width: 0.85rem; height: 0.85rem; flex-shrink: 0; }
  .ui-prefs-lang select {
    appearance: none; -webkit-appearance: none; border: 0; background: transparent; color: inherit;
    font: inherit; cursor: pointer; padding: 0; outline: none;
  }
  .ui-prefs-btn:hover, .ui-prefs-lang:hover { background: #f3f4f6; border-color: #9ca3af; color: #1e2a4a; }
  .ui-prefs-btn:focus-visible, .ui-prefs-lang:focus-within { outline: 2px solid #8b8fc7; outline-offset: 2px; }
  :root[data-theme="dark"] .ui-prefs-btn, :root[data-theme="dark"] .ui-prefs-lang { background: #1a2131; border-color: #3a4459; color: #b6bdca; }
  :root[data-theme="dark"] .ui-prefs-btn:hover, :root[data-theme="dark"] .ui-prefs-lang:hover { background: #242c3e; color: #f1f3f7; }
  .ui-prefs-standalone { position: fixed; top: 0.75rem; right: 0.75rem; z-index: 60; }
`;

const MOON = '<svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z"/></svg>';
const SUN = '<svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z"/></svg>';
const GLOBE = '<svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>';

export function initUiPrefs() {
  if (document.querySelector('.ui-prefs')) return;
  if (!document.getElementById('ui-prefs-styles')) {
    const st = document.createElement('style');
    st.id = 'ui-prefs-styles';
    st.textContent = STYLE;
    document.head.appendChild(st);
  }

  const group = document.createElement('div');
  group.className = 'ui-prefs';
  group.innerHTML = `
    <button type="button" class="ui-prefs-btn" id="ui-theme-btn"></button>
    <label class="ui-prefs-lang" title="Language / Wika">
      ${GLOBE}
      <select id="ui-lang-select" aria-label="Language / Wika">
        <option value="en">EN</option>
        <option value="fil">FIL</option>
      </select>
    </label>`;
  // Never translate the picker itself.
  group.setAttribute('data-no-translate', '');

  const themeBtn = group.querySelector('#ui-theme-btn');
  const paintThemeBtn = () => {
    const dark = currentTheme() === 'dark';
    themeBtn.innerHTML = dark ? SUN : MOON;
    const label = currentLang() === 'fil'
      ? (dark ? 'Gawing maliwanag' : 'Gawing madilim')
      : (dark ? 'Switch to light mode' : 'Switch to dark mode');
    themeBtn.setAttribute('aria-label', label);
    themeBtn.title = label;
  };
  themeBtn.addEventListener('click', () => { setTheme(currentTheme() === 'dark' ? 'light' : 'dark'); paintThemeBtn(); });
  paintThemeBtn();

  const langSel = group.querySelector('#ui-lang-select');
  langSel.value = currentLang();
  langSel.addEventListener('change', () => { setLanguage(langSel.value); paintThemeBtn(); });

  // Sit next to the date / (?) help button in the top bar.
  const dateEl = document.getElementById('current-date');
  const helpBtn = document.getElementById('page-help-btn');
  if (helpBtn) helpBtn.insertAdjacentElement('beforebegin', group);
  else if (dateEl && dateEl.parentElement) {
    if (dateEl.parentElement.tagName === 'HEADER') {
      const wrap = document.createElement('div');
      wrap.className = 'help-date-wrap';
      wrap.style.display = 'flex'; wrap.style.alignItems = 'center'; wrap.style.gap = '0.625rem';
      dateEl.parentElement.insertBefore(wrap, dateEl);
      wrap.append(group, dateEl);
    } else dateEl.insertAdjacentElement('beforebegin', group);
  } else {
    group.classList.add('ui-prefs-standalone');
    document.body.appendChild(group);
  }

  if (currentLang() === 'fil') {
    startTranslating()
      .catch(err => console.error('Could not load Filipino text:', err))
      .finally(() => document.documentElement.classList.remove('i18n-pending'));
  }
}
